In [1]:
import pandas as pd

df = pd.read_csv("titanic.csv")
df.shape

(891, 12)

In [2]:
# Average fare by passenger class
print(df.groupby("Pclass")["Fare"].mean())

Pclass
1    84.154687
2    20.662183
3    13.675550
Name: Fare, dtype: float64

In [3]:
# Survival rate by Embarked port
print(df.groupby("Embarked")["Survived"].mean())

Embarked
C    0.553571
Q    0.389610
S    0.336957
Name: Survived, dtype: float64

In [4]:
# Count of passengers by class and sex together
print(df.groupby(["Pclass","Sex"]).size())

Pclass  Sex
1       female     94
        male      122
2       female     76
        male      108
3       female    144
        male      347
dtype: int64

In [5]:
# Average age by class — is there a pattern, and what explains it?
print(df.groupby("Pclass")["Age"].mean())
# Yes, first-class passengers were older on average, likely because wealthier and older people tended to travel in first class.

Pclass
1    38.233441
2    29.877630
3    25.140620
Name: Age, dtype: float64

In [6]:
# Which class had highest survival rate, which lowest?
print(df.groupby("Pclass")["Survived"].mean())

Pclass
1    0.629630
2    0.472826
3    0.242363
Name: Survived, dtype: float64

In [7]:
df.groupby(["Pclass", "Sex"])["Survived"].mean().unstack()
# What i observed is the Output is well orgaized in bolder table 
# Six values became a grid of 3 rows × 2 columns. Same six numbers, rearranged.

Sex       female      male
Pclass
1       0.968085  0.368852
2       0.921053  0.157407
3       0.500000  0.135447

In [8]:
df.groupby("Pclass")["Age"].agg(["mean", "count"])
# Yes the third class category values are missing more than the other two classes i dont know how to fill them

             mean  count
Pclass
1       38.233441    186
2       29.877630    173
3       25.140620    355

In [9]:
# Q.7
# Third-class males had the worst survival odds because they were both male and in the lowest passenger class.