In [1]:
import pandas as pd

titanic = pd.read_csv("titanic.csv")
titanic.shape

(891, 12)

In [2]:
titanic["Name"].head()

0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
Name: Name, dtype: str

In [3]:
titanic["Name"].str.split(",").head()

0                           [Braund,  Mr. Owen Harris]
1    [Cumings,  Mrs. John Bradley (Florence Briggs ...
2                            [Heikkinen,  Miss. Laina]
3      [Futrelle,  Mrs. Jacques Heath (Lily May Peel)]
4                          [Allen,  Mr. William Henry]
Name: Name, dtype: object

In [4]:
titanic["Title"] = titanic["Name"].str.split(",").str[1].str.split(".").str[0].str.strip()
titanic["Title"].value_counts()

Title
Mr              517
Miss            182
Mrs             125
Master           40
Dr                7
Rev               6
Major             2
Mlle              2
Col               2
Don               1
Mme               1
Ms                1
Lady              1
Sir               1
Capt              1
the Countess      1
Jonkheer          1
Name: count, dtype: int64

In [5]:
titanic.groupby("Title")["Survived"].agg(["mean", "count"])

                  mean  count
Title
Capt          0.000000      1
Col           0.500000      2
Don           0.000000      1
Dr            0.428571      7
Jonkheer      0.000000      1
Lady          1.000000      1
Major         0.500000      2
Master        0.575000     40
Miss          0.697802    182
Mlle          1.000000      2
Mme           1.000000      1
Mr            0.156673    517
Mrs           0.792000    125
Ms            1.000000      1
Rev           0.000000      6
Sir           1.000000      1
the Countess  1.000000      1

In [6]:
titanic["Title"] = titanic["Title"].replace({"Mlle": "Miss", "Ms": "Miss", "Mme": "Mrs"})

common = ["Mr", "Miss", "Mrs", "Master"]
titanic["Title"] = titanic["Title"].where(titanic["Title"].isin(common), "other")

titanic.groupby("Title")["Survived"].agg(["mean", "count"])

            mean  count
Title
Master  0.575000     40
Miss    0.702703    185
Mr      0.156673    517
Mrs     0.793651    126
other   0.347826     23